# Generated by Django 3.1.3 on 2020-12-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blood_stock',
            new_name='BloodStock',
        ),
    ]
