# Generated by Django 3.1.3 on 2020-12-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0003_donor_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Blood_stock',
        ),
        migrations.RenameModel(
            old_name='Donor',
            new_name='Profile',
        ),
    ]
