# Generated by Django 3.1.3 on 2020-12-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0004_auto_20201217_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_stock',
            old_name='donor_name',
            new_name='profile_name',
        ),
    ]
