# Generated by Django 3.1.5 on 2021-01-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_auto_20201218_0950'),
        ('bloodbank', '0006_remove_blood_stock_profile_name'),
    ]

    operations = [
    ]
