# Generated by Django 3.1.3 on 2021-01-07 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0009_auto_20210106_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='hospital_name',
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donations',
            name='medical_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.condition'),
        ),
    ]
