# Generated by Django 3.1.3 on 2021-01-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0009_auto_20210106_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='id',
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='hospital',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hospital', serialize=False, to='bloodbank.hospital'),
        ),
    ]
